import { Router } from "express";
import { query, queryOne } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { mapPlan } from "../lib/mappers.js";

const router = Router();

/**
 * The three kinds of plan stored in `ai_plans`.
 *
 * "program" is a ready-made programme the user is following. It deliberately
 * lives alongside "workout" rather than replacing it: picking a programme used
 * to overwrite the user's own AI plan, which meant browsing the programme list
 * could silently destroy weeks of progression.
 */
const PLAN_TYPES = ["workout", "diet", "program"];

const activeOf = (userId, planType) =>
  queryOne(
    `SELECT * FROM ai_plans WHERE user_id = $1 AND plan_type = $2 AND is_active = true
      ORDER BY created_at DESC LIMIT 1`,
    [userId, planType]
  );

/** Active workout plan, diet plan and programme in one call (used on app boot). */
router.get("/", requireAuth, async (req, res, next) => {
  try {
    const [workout, diet, program] = await Promise.all([
      activeOf(req.userId, "workout"),
      activeOf(req.userId, "diet"),
      activeOf(req.userId, "program"),
    ]);
    res.json({ workoutPlan: mapPlan(workout), dietPlan: mapPlan(diet), activeProgram: mapPlan(program) });
  } catch (err) {
    next(err);
  }
});

/**
 * Past versions of one plan type, newest first.
 *
 * Nothing new is recorded for this — saving has always only flipped the old
 * row's `is_active`, never deleted it, so every plan the user has ever had is
 * already sitting in the table waiting to be read.
 */
router.get("/history", requireAuth, async (req, res, next) => {
  try {
    const { planType } = req.query;
    if (!PLAN_TYPES.includes(planType)) return res.status(400).json({ error: "invalid_plan_type" });
    const limit = Math.min(Math.max(Number(req.query.limit) || 20, 1), 50);

    // `limit` is inlined rather than bound because every other LIMIT in this
    // codebase is a literal; it is clamped to an integer just above.
    const rows = await query(
      `SELECT * FROM ai_plans WHERE user_id = $1 AND plan_type = $2 ORDER BY created_at DESC LIMIT ${limit}`,
      [req.userId, planType]
    );
    res.json({ plans: rows.map(mapPlan) });
  } catch (err) {
    next(err);
  }
});

/**
 * Stores a plan generated by the client-side rule engine. Saving deactivates
 * the previous plan of the same type so "active" always has one winner — and
 * that deactivated row is what the history endpoint above reads back.
 */
router.post("/", requireAuth, async (req, res, next) => {
  try {
    const { planType, plan } = req.body || {};
    if (!PLAN_TYPES.includes(planType)) return res.status(400).json({ error: "invalid_plan_type" });
    if (!plan || typeof plan !== "object") return res.status(400).json({ error: "plan_required" });

    await query("UPDATE ai_plans SET is_active = false WHERE user_id = $1 AND plan_type = $2", [req.userId, planType]);
    const rows = await query(
      "INSERT INTO ai_plans (user_id, plan_type, plan_json) VALUES ($1, $2, $3) RETURNING *",
      [req.userId, planType, JSON.stringify(plan)]
    );

    // The column now means what its name says — which ready-made programme is
    // running. Saving a workout plan no longer writes 'ai-plan' over it, since
    // the two are independent and can be active at the same time.
    if (planType === "program") {
      await query("UPDATE profiles SET active_program_id = $2, updated_at = now() WHERE user_id = $1", [
        req.userId,
        typeof plan.programId === "string" ? plan.programId.slice(0, 60) : null,
      ]);
    }

    res.status(201).json({ plan: mapPlan(rows[0]) });
  } catch (err) {
    next(err);
  }
});

router.delete("/:planType", requireAuth, async (req, res, next) => {
  try {
    const { planType } = req.params;
    if (!PLAN_TYPES.includes(planType)) return res.status(400).json({ error: "invalid_plan_type" });
    await query("UPDATE ai_plans SET is_active = false WHERE user_id = $1 AND plan_type = $2", [req.userId, planType]);
    if (planType === "program") {
      await query("UPDATE profiles SET active_program_id = NULL, updated_at = now() WHERE user_id = $1", [req.userId]);
    }
    res.status(204).end();
  } catch (err) {
    next(err);
  }
});

export default router;
