import { Router } from "express";
import { query, queryOne } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { mapPlan } from "../lib/mappers.js";

const router = Router();

/** Active workout and diet plans in one call (used on app boot). */
router.get("/", requireAuth, async (req, res, next) => {
  try {
    const [workout, diet] = await Promise.all([
      queryOne(
        `SELECT * FROM ai_plans WHERE user_id = $1 AND plan_type = 'workout' AND is_active = true
          ORDER BY created_at DESC LIMIT 1`,
        [req.userId]
      ),
      queryOne(
        `SELECT * FROM ai_plans WHERE user_id = $1 AND plan_type = 'diet' AND is_active = true
          ORDER BY created_at DESC LIMIT 1`,
        [req.userId]
      ),
    ]);
    res.json({ workoutPlan: mapPlan(workout), dietPlan: mapPlan(diet) });
  } catch (err) {
    next(err);
  }
});

/**
 * Stores a plan generated by the client-side rule engine. Saving deactivates
 * the previous plan of the same type so "active" always has one winner.
 */
router.post("/", requireAuth, async (req, res, next) => {
  try {
    const { planType, plan } = req.body || {};
    if (!["workout", "diet"].includes(planType)) return res.status(400).json({ error: "invalid_plan_type" });
    if (!plan || typeof plan !== "object") return res.status(400).json({ error: "plan_required" });

    await query("UPDATE ai_plans SET is_active = false WHERE user_id = $1 AND plan_type = $2", [req.userId, planType]);
    const rows = await query(
      "INSERT INTO ai_plans (user_id, plan_type, plan_json) VALUES ($1, $2, $3) RETURNING *",
      [req.userId, planType, JSON.stringify(plan)]
    );

    // An AI plan replaces any pre-made program the user had selected.
    if (planType === "workout") {
      await query("UPDATE profiles SET active_program_id = 'ai-plan', updated_at = now() WHERE user_id = $1", [req.userId]);
    }

    res.status(201).json({ plan: mapPlan(rows[0]) });
  } catch (err) {
    next(err);
  }
});

router.delete("/:planType", requireAuth, async (req, res, next) => {
  try {
    const { planType } = req.params;
    if (!["workout", "diet"].includes(planType)) return res.status(400).json({ error: "invalid_plan_type" });
    await query("UPDATE ai_plans SET is_active = false WHERE user_id = $1 AND plan_type = $2", [req.userId, planType]);
    if (planType === "workout") {
      await query("UPDATE profiles SET active_program_id = NULL, updated_at = now() WHERE user_id = $1", [req.userId]);
    }
    res.status(204).end();
  } catch (err) {
    next(err);
  }
});

export default router;
